### ISSUE TITLE
The module it's not working

### ISSUE THREAD

**Issue by NicKoehler** [alessandromaggio/pythonping#25]
I tryed to use this module following the "basic usage" on [this site](https://pypi.org/project/pythonping/)

I installed the module and I wrote:

`from pythonping import ping`
`ping('127.0.0.1', verbose=True)`

I only received a bunch of errors like following

> Traceback (most recent call last):
  File "/home/nic/.vscode-oss/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/nic/.vscode-oss/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/nic/.vscode-oss/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib64/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nic/Python/Telegram_bot_elo/brawl.py", line 129, in <module>
    ping("pingtest-ams.brawlhalla.com")
  File "/home/nic/Python/Telegram_bot_elo/brawl/lib/python3.7/site-packages/pythonping/__init__.py", line 52, in ping
    comm = executor.Communicator(target, provider, timeout, socket_options=options, verbose=verbose, output=out)
  File "/home/nic/Python/Telegram_bot_elo/brawl/lib/python3.7/site-packages/pythonping/executor.py", line 224, in __init__
    self.socket = network.Socket(target, 'icmp', source=None, options=socket_options)
  File "/home/nic/Python/Telegram_bot_elo/brawl/lib/python3.7/site-packages/pythonping/network.py", line 25, in __init__
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, self.protocol)
  File "/usr/lib64/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function Socket.__del__ at 0x7fae1b5595f0>
Traceback (most recent call last):
  File "/home/nic/Python/Telegram_bot_elo/brawl/lib/python3.7/site-packages/pythonping/network.py", line 56, in __del__
    if self.socket:
AttributeError: 'Socket' object has no attribute 'socket'
Exception ignored in: <function Communicator.__del__ at 0x7fae188c8200>
Traceback (most recent call last):
  File "/home/nic/Python/Telegram_bot_elo/brawl/lib/python3.7/site-packages/pythonping/executor.py", line 233, in __del__
    if self.socket:
AttributeError: 'Communicator' object has no attribute 'socket'

I'm doing something wrong?

**My system:**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.60.0
Qt Version: 5.13.0
Kernel Version: 4.19.66-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 15,5 GiB
Python Version: 3.7.4

**Comment by alessandromaggio** [comment]
Are you running as root?

**Comment by NicKoehler** [comment]
> Are you running as root?

I'm running it from a virtual environment as user

![Screenshot_20190903_210102](https://user-images.githubusercontent.com/53040044/64201024-f3f2d880-ce8d-11e9-987c-c111045de11c.png)

this is the screenshot if it could help

**Comment by alessandromaggio** [comment]
I understand, but this does not imply _any root privilege_.
The module requires root privileges to be run, try with `sudo python brawl.py`.
